/**
 * generated by Xtext 2.12.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl;

import fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.DropMessage;
import fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouterDslPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Drop Message</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DropMessageImpl extends MessageDecisionImpl implements DropMessage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DropMessageImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RouterDslPackage.Literals.DROP_MESSAGE;
  }

} //DropMessageImpl
