/**
 * generated by Xtext 2.12.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl;

import fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ObjectAccess;
import fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouterDslPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Object Access</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ObjectAccessImpl extends ObjectAccessOrValueImpl implements ObjectAccess
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ObjectAccessImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RouterDslPackage.Literals.OBJECT_ACCESS;
  }

} //ObjectAccessImpl
