/**
 * generated by Xtext 2.12.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl;

import fr.obeo.dsl.designer.sample.flow.Processor;

import fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAccess;
import fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAttribute;
import fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouterDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Processor Access</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ProcessorAccessImpl#getProcessor <em>Processor</em>}</li>
 *   <li>{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ProcessorAccessImpl#getAttribute <em>Attribute</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProcessorAccessImpl extends ObjectAccessImpl implements ProcessorAccess
{
  /**
   * The cached value of the '{@link #getProcessor() <em>Processor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProcessor()
   * @generated
   * @ordered
   */
  protected Processor processor;

  /**
   * The default value of the '{@link #getAttribute() <em>Attribute</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttribute()
   * @generated
   * @ordered
   */
  protected static final ProcessorAttribute ATTRIBUTE_EDEFAULT = ProcessorAttribute.CAPACITY;

  /**
   * The cached value of the '{@link #getAttribute() <em>Attribute</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttribute()
   * @generated
   * @ordered
   */
  protected ProcessorAttribute attribute = ATTRIBUTE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProcessorAccessImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RouterDslPackage.Literals.PROCESSOR_ACCESS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Processor getProcessor()
  {
    if (processor != null && processor.eIsProxy())
    {
      InternalEObject oldProcessor = (InternalEObject)processor;
      processor = (Processor)eResolveProxy(oldProcessor);
      if (processor != oldProcessor)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, RouterDslPackage.PROCESSOR_ACCESS__PROCESSOR, oldProcessor, processor));
      }
    }
    return processor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Processor basicGetProcessor()
  {
    return processor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setProcessor(Processor newProcessor)
  {
    Processor oldProcessor = processor;
    processor = newProcessor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RouterDslPackage.PROCESSOR_ACCESS__PROCESSOR, oldProcessor, processor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessorAttribute getAttribute()
  {
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAttribute(ProcessorAttribute newAttribute)
  {
    ProcessorAttribute oldAttribute = attribute;
    attribute = newAttribute == null ? ATTRIBUTE_EDEFAULT : newAttribute;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RouterDslPackage.PROCESSOR_ACCESS__ATTRIBUTE, oldAttribute, attribute));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RouterDslPackage.PROCESSOR_ACCESS__PROCESSOR:
        if (resolve) return getProcessor();
        return basicGetProcessor();
      case RouterDslPackage.PROCESSOR_ACCESS__ATTRIBUTE:
        return getAttribute();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RouterDslPackage.PROCESSOR_ACCESS__PROCESSOR:
        setProcessor((Processor)newValue);
        return;
      case RouterDslPackage.PROCESSOR_ACCESS__ATTRIBUTE:
        setAttribute((ProcessorAttribute)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RouterDslPackage.PROCESSOR_ACCESS__PROCESSOR:
        setProcessor((Processor)null);
        return;
      case RouterDslPackage.PROCESSOR_ACCESS__ATTRIBUTE:
        setAttribute(ATTRIBUTE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RouterDslPackage.PROCESSOR_ACCESS__PROCESSOR:
        return processor != null;
      case RouterDslPackage.PROCESSOR_ACCESS__ATTRIBUTE:
        return attribute != ATTRIBUTE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (attribute: ");
    result.append(attribute);
    result.append(')');
    return result.toString();
  }

} //ProcessorAccessImpl
