/**
 * generated by Xtext 2.11.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl;

import fr.obeo.dsl.designer.sample.flow.routerdsl.RouterDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RouterDslStandaloneSetup extends RouterDslStandaloneSetupGenerated {
  public static void doSetup() {
    new RouterDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
