/**
 * generated by Xtext 2.11.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl;

import fr.obeo.dsl.designer.sample.flow.routerdsl.AbstractRouterDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RouterDslRuntimeModule extends AbstractRouterDslRuntimeModule {
}
