/**
 * generated by Xtext 2.11.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl;

import fr.obeo.dsl.designer.sample.flow.routerdsl.AbstractRouterDslRuntimeModule;
import fr.obeo.dsl.designer.sample.flow.routerdsl.scoping.RouterGlobalScopeProvider;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RouterDslRuntimeModule extends AbstractRouterDslRuntimeModule {
  @Override
  public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
    return RouterGlobalScopeProvider.class;
  }
}
