/*
 * generated by Xtext 2.11.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RouterDslRuntimeModule extends AbstractRouterDslRuntimeModule {
}
