/*
 * generated by Xtext 2.11.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RouterDslStandaloneSetup extends RouterDslStandaloneSetupGenerated {

	def static void doSetup() {
		new RouterDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
