/**
 * generated by Xtext 2.11.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.ide;

import fr.obeo.dsl.designer.sample.flow.routerdsl.ide.AbstractRouterDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RouterDslIdeModule extends AbstractRouterDslIdeModule {
}
