/**
 * generated by Xtext 2.11.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.obeo.dsl.designer.sample.flow.routerdsl.RouterDslRuntimeModule;
import fr.obeo.dsl.designer.sample.flow.routerdsl.RouterDslStandaloneSetup;
import fr.obeo.dsl.designer.sample.flow.routerdsl.ide.RouterDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RouterDslIdeSetup extends RouterDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    RouterDslRuntimeModule _routerDslRuntimeModule = new RouterDslRuntimeModule();
    RouterDslIdeModule _routerDslIdeModule = new RouterDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_routerDslRuntimeModule, _routerDslIdeModule));
  }
}
