/**
 * generated by Xtext 2.11.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.ui;

import fr.obeo.dsl.designer.sample.flow.routerdsl.ui.AbstractRouterDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RouterDslUiModule extends AbstractRouterDslUiModule {
  public RouterDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
