/**
 * generated by Xtext 2.11.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.ui.contentassist;

import fr.obeo.dsl.designer.sample.flow.routerdsl.ui.contentassist.AbstractRouterDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RouterDslProposalProvider extends AbstractRouterDslProposalProvider {
}
