/**
 * generated by Xtext 2.12.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Drop Message</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouterDslPackage#getDropMessage()
 * @model
 * @generated
 */
public interface DropMessage extends MessageDecision
{
} // DropMessage
