/**
 * generated by Xtext 2.12.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Message Decision</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouterDslPackage#getMessageDecision()
 * @model
 * @generated
 */
public interface MessageDecision extends Decision
{
} // MessageDecision
