/**
 * generated by Xtext 2.12.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl;

import fr.obeo.dsl.designer.sample.flow.Processor;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Processor Access</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAccess#getProcessor <em>Processor</em>}</li>
 *   <li>{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAccess#getAttribute <em>Attribute</em>}</li>
 * </ul>
 *
 * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouterDslPackage#getProcessorAccess()
 * @model
 * @generated
 */
public interface ProcessorAccess extends ObjectAccess
{
  /**
   * Returns the value of the '<em><b>Processor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Processor</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Processor</em>' reference.
   * @see #setProcessor(Processor)
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouterDslPackage#getProcessorAccess_Processor()
   * @model
   * @generated
   */
  Processor getProcessor();

  /**
   * Sets the value of the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAccess#getProcessor <em>Processor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Processor</em>' reference.
   * @see #getProcessor()
   * @generated
   */
  void setProcessor(Processor value);

  /**
   * Returns the value of the '<em><b>Attribute</b></em>' attribute.
   * The literals are from the enumeration {@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAttribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attribute</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' attribute.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAttribute
   * @see #setAttribute(ProcessorAttribute)
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouterDslPackage#getProcessorAccess_Attribute()
   * @model
   * @generated
   */
  ProcessorAttribute getAttribute();

  /**
   * Sets the value of the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAccess#getAttribute <em>Attribute</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' attribute.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAttribute
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(ProcessorAttribute value);

} // ProcessorAccess
