/**
 * generated by Xtext 2.12.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouterDslFactory
 * @model kind="package"
 * @generated
 */
public interface RouterDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "routerDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.obeo.fr/dsl/designer/sample/flow/routerdsl/RouterDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "routerDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RouterDslPackage eINSTANCE = fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RoutingRulesImpl <em>Routing Rules</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RoutingRulesImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getRoutingRules()
   * @generated
   */
  int ROUTING_RULES = 0;

  /**
   * The number of structural features of the '<em>Routing Rules</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTING_RULES_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.CaseRuleImpl <em>Case Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.CaseRuleImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getCaseRule()
   * @generated
   */
  int CASE_RULE = 1;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_RULE__CONDITION = 0;

  /**
   * The feature id for the '<em><b>Decisions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_RULE__DECISIONS = 1;

  /**
   * The number of structural features of the '<em>Case Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_RULE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.DecisionImpl <em>Decision</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.DecisionImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getDecision()
   * @generated
   */
  int DECISION = 2;

  /**
   * The number of structural features of the '<em>Decision</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.MessageDecisionImpl <em>Message Decision</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.MessageDecisionImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getMessageDecision()
   * @generated
   */
  int MESSAGE_DECISION = 3;

  /**
   * The number of structural features of the '<em>Message Decision</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_DECISION_FEATURE_COUNT = DECISION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouteToImpl <em>Route To</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouteToImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getRouteTo()
   * @generated
   */
  int ROUTE_TO = 4;

  /**
   * The feature id for the '<em><b>Destination</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTE_TO__DESTINATION = DECISION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Route To</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTE_TO_FEATURE_COUNT = DECISION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.DropMessageImpl <em>Drop Message</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.DropMessageImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getDropMessage()
   * @generated
   */
  int DROP_MESSAGE = 5;

  /**
   * The number of structural features of the '<em>Drop Message</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP_MESSAGE_FEATURE_COUNT = MESSAGE_DECISION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.AlertImpl <em>Alert</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.AlertImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getAlert()
   * @generated
   */
  int ALERT = 6;

  /**
   * The feature id for the '<em><b>Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALERT__LEVEL = MESSAGE_DECISION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Alert</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALERT_FEATURE_COUNT = MESSAGE_DECISION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ConditionalImpl <em>Conditional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ConditionalImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getConditional()
   * @generated
   */
  int CONDITIONAL = 7;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL__LEFT = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL__OP = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Conditional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ObjectAccessOrValueImpl <em>Object Access Or Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ObjectAccessOrValueImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getObjectAccessOrValue()
   * @generated
   */
  int OBJECT_ACCESS_OR_VALUE = 8;

  /**
   * The number of structural features of the '<em>Object Access Or Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_ACCESS_OR_VALUE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.LiteralValueImpl <em>Literal Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.LiteralValueImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getLiteralValue()
   * @generated
   */
  int LITERAL_VALUE = 9;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL_VALUE__VALUE = OBJECT_ACCESS_OR_VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Literal Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL_VALUE_FEATURE_COUNT = OBJECT_ACCESS_OR_VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ThroughtputImpl <em>Throughtput</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ThroughtputImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getThroughtput()
   * @generated
   */
  int THROUGHTPUT = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THROUGHTPUT__VALUE = OBJECT_ACCESS_OR_VALUE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THROUGHTPUT__UNIT = OBJECT_ACCESS_OR_VALUE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Throughtput</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THROUGHTPUT_FEATURE_COUNT = OBJECT_ACCESS_OR_VALUE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.TemperatureImpl <em>Temperature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.TemperatureImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getTemperature()
   * @generated
   */
  int TEMPERATURE = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMPERATURE__VALUE = OBJECT_ACCESS_OR_VALUE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMPERATURE__UNIT = OBJECT_ACCESS_OR_VALUE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Temperature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMPERATURE_FEATURE_COUNT = OBJECT_ACCESS_OR_VALUE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ObjectAccessImpl <em>Object Access</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ObjectAccessImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getObjectAccess()
   * @generated
   */
  int OBJECT_ACCESS = 12;

  /**
   * The number of structural features of the '<em>Object Access</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_ACCESS_FEATURE_COUNT = OBJECT_ACCESS_OR_VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ProcessorAccessImpl <em>Processor Access</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ProcessorAccessImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getProcessorAccess()
   * @generated
   */
  int PROCESSOR_ACCESS = 13;

  /**
   * The feature id for the '<em><b>Processor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESSOR_ACCESS__PROCESSOR = OBJECT_ACCESS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Attribute</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESSOR_ACCESS__ATTRIBUTE = OBJECT_ACCESS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Processor Access</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESSOR_ACCESS_FEATURE_COUNT = OBJECT_ACCESS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.SensorAccessImpl <em>Sensor Access</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.SensorAccessImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getSensorAccess()
   * @generated
   */
  int SENSOR_ACCESS = 14;

  /**
   * The feature id for the '<em><b>Sensor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_ACCESS__SENSOR = OBJECT_ACCESS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sensor Access</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_ACCESS_FEATURE_COUNT = OBJECT_ACCESS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.SystemAccessImpl <em>System Access</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.SystemAccessImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getSystemAccess()
   * @generated
   */
  int SYSTEM_ACCESS = 15;

  /**
   * The feature id for the '<em><b>System</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_ACCESS__SYSTEM = OBJECT_ACCESS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>System Access</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_ACCESS_FEATURE_COUNT = OBJECT_ACCESS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RoutingRuleImpl <em>Routing Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RoutingRuleImpl
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getRoutingRule()
   * @generated
   */
  int ROUTING_RULE = 16;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTING_RULE__RULES = ROUTING_RULES_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Routing Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTING_RULE_FEATURE_COUNT = ROUTING_RULES_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SensorAttribute <em>Sensor Attribute</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SensorAttribute
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getSensorAttribute()
   * @generated
   */
  int SENSOR_ATTRIBUTE = 17;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAttribute <em>Processor Attribute</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAttribute
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getProcessorAttribute()
   * @generated
   */
  int PROCESSOR_ATTRIBUTE = 18;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Comparison <em>Comparison</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Comparison
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getComparison()
   * @generated
   */
  int COMPARISON = 19;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.TimeUnit <em>Time Unit</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.TimeUnit
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getTimeUnit()
   * @generated
   */
  int TIME_UNIT = 20;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.TemperatureUnit <em>Temperature Unit</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.TemperatureUnit
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getTemperatureUnit()
   * @generated
   */
  int TEMPERATURE_UNIT = 21;

  /**
   * The meta object id for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.AlertLevel <em>Alert Level</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.AlertLevel
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getAlertLevel()
   * @generated
   */
  int ALERT_LEVEL = 22;


  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RoutingRules <em>Routing Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Routing Rules</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RoutingRules
   * @generated
   */
  EClass getRoutingRules();

  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.CaseRule <em>Case Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Case Rule</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.CaseRule
   * @generated
   */
  EClass getCaseRule();

  /**
   * Returns the meta object for the containment reference '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.CaseRule#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.CaseRule#getCondition()
   * @see #getCaseRule()
   * @generated
   */
  EReference getCaseRule_Condition();

  /**
   * Returns the meta object for the containment reference list '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.CaseRule#getDecisions <em>Decisions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Decisions</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.CaseRule#getDecisions()
   * @see #getCaseRule()
   * @generated
   */
  EReference getCaseRule_Decisions();

  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Decision <em>Decision</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decision</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Decision
   * @generated
   */
  EClass getDecision();

  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.MessageDecision <em>Message Decision</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message Decision</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.MessageDecision
   * @generated
   */
  EClass getMessageDecision();

  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouteTo <em>Route To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Route To</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouteTo
   * @generated
   */
  EClass getRouteTo();

  /**
   * Returns the meta object for the reference '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouteTo#getDestination <em>Destination</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Destination</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouteTo#getDestination()
   * @see #getRouteTo()
   * @generated
   */
  EReference getRouteTo_Destination();

  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.DropMessage <em>Drop Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Drop Message</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.DropMessage
   * @generated
   */
  EClass getDropMessage();

  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Alert <em>Alert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alert</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Alert
   * @generated
   */
  EClass getAlert();

  /**
   * Returns the meta object for the attribute '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Alert#getLevel <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Level</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Alert#getLevel()
   * @see #getAlert()
   * @generated
   */
  EAttribute getAlert_Level();

  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Conditional <em>Conditional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conditional</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Conditional
   * @generated
   */
  EClass getConditional();

  /**
   * Returns the meta object for the containment reference '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Conditional#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Conditional#getLeft()
   * @see #getConditional()
   * @generated
   */
  EReference getConditional_Left();

  /**
   * Returns the meta object for the attribute '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Conditional#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Conditional#getOp()
   * @see #getConditional()
   * @generated
   */
  EAttribute getConditional_Op();

  /**
   * Returns the meta object for the containment reference '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Conditional#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Conditional#getRight()
   * @see #getConditional()
   * @generated
   */
  EReference getConditional_Right();

  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ObjectAccessOrValue <em>Object Access Or Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Access Or Value</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ObjectAccessOrValue
   * @generated
   */
  EClass getObjectAccessOrValue();

  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.LiteralValue <em>Literal Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Literal Value</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.LiteralValue
   * @generated
   */
  EClass getLiteralValue();

  /**
   * Returns the meta object for the attribute '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.LiteralValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.LiteralValue#getValue()
   * @see #getLiteralValue()
   * @generated
   */
  EAttribute getLiteralValue_Value();

  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Throughtput <em>Throughtput</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Throughtput</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Throughtput
   * @generated
   */
  EClass getThroughtput();

  /**
   * Returns the meta object for the attribute '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Throughtput#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Throughtput#getValue()
   * @see #getThroughtput()
   * @generated
   */
  EAttribute getThroughtput_Value();

  /**
   * Returns the meta object for the attribute '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Throughtput#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Throughtput#getUnit()
   * @see #getThroughtput()
   * @generated
   */
  EAttribute getThroughtput_Unit();

  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Temperature <em>Temperature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Temperature</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Temperature
   * @generated
   */
  EClass getTemperature();

  /**
   * Returns the meta object for the attribute '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Temperature#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Temperature#getValue()
   * @see #getTemperature()
   * @generated
   */
  EAttribute getTemperature_Value();

  /**
   * Returns the meta object for the attribute '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Temperature#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Temperature#getUnit()
   * @see #getTemperature()
   * @generated
   */
  EAttribute getTemperature_Unit();

  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ObjectAccess <em>Object Access</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Access</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ObjectAccess
   * @generated
   */
  EClass getObjectAccess();

  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAccess <em>Processor Access</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Processor Access</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAccess
   * @generated
   */
  EClass getProcessorAccess();

  /**
   * Returns the meta object for the reference '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAccess#getProcessor <em>Processor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Processor</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAccess#getProcessor()
   * @see #getProcessorAccess()
   * @generated
   */
  EReference getProcessorAccess_Processor();

  /**
   * Returns the meta object for the attribute '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAccess#getAttribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attribute</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAccess#getAttribute()
   * @see #getProcessorAccess()
   * @generated
   */
  EAttribute getProcessorAccess_Attribute();

  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SensorAccess <em>Sensor Access</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor Access</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SensorAccess
   * @generated
   */
  EClass getSensorAccess();

  /**
   * Returns the meta object for the reference '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SensorAccess#getSensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sensor</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SensorAccess#getSensor()
   * @see #getSensorAccess()
   * @generated
   */
  EReference getSensorAccess_Sensor();

  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SystemAccess <em>System Access</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Access</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SystemAccess
   * @generated
   */
  EClass getSystemAccess();

  /**
   * Returns the meta object for the reference '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SystemAccess#getSystem <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>System</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SystemAccess#getSystem()
   * @see #getSystemAccess()
   * @generated
   */
  EReference getSystemAccess_System();

  /**
   * Returns the meta object for class '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RoutingRule <em>Routing Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Routing Rule</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RoutingRule
   * @generated
   */
  EClass getRoutingRule();

  /**
   * Returns the meta object for the containment reference list '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RoutingRule#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RoutingRule#getRules()
   * @see #getRoutingRule()
   * @generated
   */
  EReference getRoutingRule_Rules();

  /**
   * Returns the meta object for enum '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SensorAttribute <em>Sensor Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Sensor Attribute</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SensorAttribute
   * @generated
   */
  EEnum getSensorAttribute();

  /**
   * Returns the meta object for enum '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAttribute <em>Processor Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Processor Attribute</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAttribute
   * @generated
   */
  EEnum getProcessorAttribute();

  /**
   * Returns the meta object for enum '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Comparison <em>Comparison</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Comparison</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Comparison
   * @generated
   */
  EEnum getComparison();

  /**
   * Returns the meta object for enum '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.TimeUnit <em>Time Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Time Unit</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.TimeUnit
   * @generated
   */
  EEnum getTimeUnit();

  /**
   * Returns the meta object for enum '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.TemperatureUnit <em>Temperature Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Temperature Unit</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.TemperatureUnit
   * @generated
   */
  EEnum getTemperatureUnit();

  /**
   * Returns the meta object for enum '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.AlertLevel <em>Alert Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Alert Level</em>'.
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.AlertLevel
   * @generated
   */
  EEnum getAlertLevel();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RouterDslFactory getRouterDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RoutingRulesImpl <em>Routing Rules</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RoutingRulesImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getRoutingRules()
     * @generated
     */
    EClass ROUTING_RULES = eINSTANCE.getRoutingRules();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.CaseRuleImpl <em>Case Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.CaseRuleImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getCaseRule()
     * @generated
     */
    EClass CASE_RULE = eINSTANCE.getCaseRule();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CASE_RULE__CONDITION = eINSTANCE.getCaseRule_Condition();

    /**
     * The meta object literal for the '<em><b>Decisions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CASE_RULE__DECISIONS = eINSTANCE.getCaseRule_Decisions();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.DecisionImpl <em>Decision</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.DecisionImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getDecision()
     * @generated
     */
    EClass DECISION = eINSTANCE.getDecision();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.MessageDecisionImpl <em>Message Decision</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.MessageDecisionImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getMessageDecision()
     * @generated
     */
    EClass MESSAGE_DECISION = eINSTANCE.getMessageDecision();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouteToImpl <em>Route To</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouteToImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getRouteTo()
     * @generated
     */
    EClass ROUTE_TO = eINSTANCE.getRouteTo();

    /**
     * The meta object literal for the '<em><b>Destination</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROUTE_TO__DESTINATION = eINSTANCE.getRouteTo_Destination();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.DropMessageImpl <em>Drop Message</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.DropMessageImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getDropMessage()
     * @generated
     */
    EClass DROP_MESSAGE = eINSTANCE.getDropMessage();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.AlertImpl <em>Alert</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.AlertImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getAlert()
     * @generated
     */
    EClass ALERT = eINSTANCE.getAlert();

    /**
     * The meta object literal for the '<em><b>Level</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALERT__LEVEL = eINSTANCE.getAlert_Level();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ConditionalImpl <em>Conditional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ConditionalImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getConditional()
     * @generated
     */
    EClass CONDITIONAL = eINSTANCE.getConditional();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONAL__LEFT = eINSTANCE.getConditional_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITIONAL__OP = eINSTANCE.getConditional_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONAL__RIGHT = eINSTANCE.getConditional_Right();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ObjectAccessOrValueImpl <em>Object Access Or Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ObjectAccessOrValueImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getObjectAccessOrValue()
     * @generated
     */
    EClass OBJECT_ACCESS_OR_VALUE = eINSTANCE.getObjectAccessOrValue();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.LiteralValueImpl <em>Literal Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.LiteralValueImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getLiteralValue()
     * @generated
     */
    EClass LITERAL_VALUE = eINSTANCE.getLiteralValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LITERAL_VALUE__VALUE = eINSTANCE.getLiteralValue_Value();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ThroughtputImpl <em>Throughtput</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ThroughtputImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getThroughtput()
     * @generated
     */
    EClass THROUGHTPUT = eINSTANCE.getThroughtput();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute THROUGHTPUT__VALUE = eINSTANCE.getThroughtput_Value();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute THROUGHTPUT__UNIT = eINSTANCE.getThroughtput_Unit();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.TemperatureImpl <em>Temperature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.TemperatureImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getTemperature()
     * @generated
     */
    EClass TEMPERATURE = eINSTANCE.getTemperature();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEMPERATURE__VALUE = eINSTANCE.getTemperature_Value();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEMPERATURE__UNIT = eINSTANCE.getTemperature_Unit();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ObjectAccessImpl <em>Object Access</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ObjectAccessImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getObjectAccess()
     * @generated
     */
    EClass OBJECT_ACCESS = eINSTANCE.getObjectAccess();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ProcessorAccessImpl <em>Processor Access</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.ProcessorAccessImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getProcessorAccess()
     * @generated
     */
    EClass PROCESSOR_ACCESS = eINSTANCE.getProcessorAccess();

    /**
     * The meta object literal for the '<em><b>Processor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESSOR_ACCESS__PROCESSOR = eINSTANCE.getProcessorAccess_Processor();

    /**
     * The meta object literal for the '<em><b>Attribute</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESSOR_ACCESS__ATTRIBUTE = eINSTANCE.getProcessorAccess_Attribute();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.SensorAccessImpl <em>Sensor Access</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.SensorAccessImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getSensorAccess()
     * @generated
     */
    EClass SENSOR_ACCESS = eINSTANCE.getSensorAccess();

    /**
     * The meta object literal for the '<em><b>Sensor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR_ACCESS__SENSOR = eINSTANCE.getSensorAccess_Sensor();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.SystemAccessImpl <em>System Access</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.SystemAccessImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getSystemAccess()
     * @generated
     */
    EClass SYSTEM_ACCESS = eINSTANCE.getSystemAccess();

    /**
     * The meta object literal for the '<em><b>System</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_ACCESS__SYSTEM = eINSTANCE.getSystemAccess_System();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RoutingRuleImpl <em>Routing Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RoutingRuleImpl
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getRoutingRule()
     * @generated
     */
    EClass ROUTING_RULE = eINSTANCE.getRoutingRule();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROUTING_RULE__RULES = eINSTANCE.getRoutingRule_Rules();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SensorAttribute <em>Sensor Attribute</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SensorAttribute
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getSensorAttribute()
     * @generated
     */
    EEnum SENSOR_ATTRIBUTE = eINSTANCE.getSensorAttribute();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAttribute <em>Processor Attribute</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.ProcessorAttribute
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getProcessorAttribute()
     * @generated
     */
    EEnum PROCESSOR_ATTRIBUTE = eINSTANCE.getProcessorAttribute();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Comparison <em>Comparison</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.Comparison
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getComparison()
     * @generated
     */
    EEnum COMPARISON = eINSTANCE.getComparison();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.TimeUnit <em>Time Unit</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.TimeUnit
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getTimeUnit()
     * @generated
     */
    EEnum TIME_UNIT = eINSTANCE.getTimeUnit();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.TemperatureUnit <em>Temperature Unit</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.TemperatureUnit
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getTemperatureUnit()
     * @generated
     */
    EEnum TEMPERATURE_UNIT = eINSTANCE.getTemperatureUnit();

    /**
     * The meta object literal for the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.AlertLevel <em>Alert Level</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.AlertLevel
     * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.impl.RouterDslPackageImpl#getAlertLevel()
     * @generated
     */
    EEnum ALERT_LEVEL = eINSTANCE.getAlertLevel();

  }

} //RouterDslPackage
