/**
 * generated by Xtext 2.12.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor Access</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SensorAccess#getSensor <em>Sensor</em>}</li>
 * </ul>
 *
 * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouterDslPackage#getSensorAccess()
 * @model
 * @generated
 */
public interface SensorAccess extends ObjectAccess
{
  /**
   * Returns the value of the '<em><b>Sensor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sensor</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sensor</em>' reference.
   * @see #setSensor(DataSourceDeclaration)
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouterDslPackage#getSensorAccess_Sensor()
   * @model
   * @generated
   */
  DataSourceDeclaration getSensor();

  /**
   * Sets the value of the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SensorAccess#getSensor <em>Sensor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sensor</em>' reference.
   * @see #getSensor()
   * @generated
   */
  void setSensor(DataSourceDeclaration value);

} // SensorAccess
