/**
 * generated by Xtext 2.12.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System Access</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SystemAccess#getSystem <em>System</em>}</li>
 * </ul>
 *
 * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouterDslPackage#getSystemAccess()
 * @model
 * @generated
 */
public interface SystemAccess extends ObjectAccess
{
  /**
   * Returns the value of the '<em><b>System</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>System</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>System</em>' reference.
   * @see #setSystem(SystemDeclaration)
   * @see fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.RouterDslPackage#getSystemAccess_System()
   * @model
   * @generated
   */
  SystemDeclaration getSystem();

  /**
   * Sets the value of the '{@link fr.obeo.dsl.designer.sample.flow.routerdsl.routerDsl.SystemAccess#getSystem <em>System</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>System</em>' reference.
   * @see #getSystem()
   * @generated
   */
  void setSystem(SystemDeclaration value);

} // SystemAccess
