/*
 * generated by Xtext 2.11.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.ide


/**
 * Use this class to register ide components.
 */
class RouterDslIdeModule extends AbstractRouterDslIdeModule {
}
