/**
 * generated by Xtext 2.11.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class RouterDslDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
