/**
 * generated by Xtext 2.11.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.scoping;

import fr.obeo.dsl.designer.sample.flow.routerdsl.scoping.AbstractRouterDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class RouterDslScopeProvider extends AbstractRouterDslScopeProvider {
}
