/**
 * generated by Xtext 2.11.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.validation;

import fr.obeo.dsl.designer.sample.flow.routerdsl.validation.AbstractRouterDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RouterDslValidator extends AbstractRouterDslValidator {
}
