/*
 * generated by Xtext 2.12.0
 */
package fr.obeo.dsl.designer.sample.flow.routerdsl.parser.antlr;

import com.google.inject.Inject;
import fr.obeo.dsl.designer.sample.flow.routerdsl.parser.antlr.internal.InternalRouterDslParser;
import fr.obeo.dsl.designer.sample.flow.routerdsl.services.RouterDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RouterDslParser extends AbstractAntlrParser {

	@Inject
	private RouterDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRouterDslParser createParser(XtextTokenStream stream) {
		return new InternalRouterDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RoutingRules";
	}

	public RouterDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RouterDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
